services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    ports:
      - "8888:8888"
    entrypoint: jupyter lab
    volumes:
      - type: bind
        source: ./home
        target: /root/home
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
