services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    ports:
      - "80:8888"
    entrypoint: jupyter-lab
    volumes:
      - type: bind
        source: ./home
        target: /root/home
